//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_ActionInfo
    {
        public System.Guid Id { get; set; }
        public string CategoryName { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool IsEnable { get; set; }
        public bool IsVisible { get; set; }
        public bool IsLog { get; set; }
        public int Operation { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public System.Guid MenuId { get; set; }
    }
}
