//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Oct_FrameworkEntities : DbContext
    {
        public Oct_FrameworkEntities()
            : base("name=Oct_FrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Common_ActionInfo> Common_ActionInfo { get; set; }
        public DbSet<Common_MenuInfo> Common_MenuInfo { get; set; }
        public DbSet<Common_RoleAction> Common_RoleAction { get; set; }
        public DbSet<Common_RoleInfo> Common_RoleInfo { get; set; }
        public DbSet<Common_User> Common_User { get; set; }
        public DbSet<Common_UserRole> Common_UserRole { get; set; }
        public DbSet<TestT> TestTs { get; set; }
    }
}
